name: dartvex_flutter_example
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dartvex_flutter:
    path: ../

flutter:
  uses-material-design: true
